from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)

DOMAIN = "growatt_tcp"
DEFAULT_PORT = 502
DEFAULT_SLAVE = 1

SYSTEM_STATUS_MAP = {
    0: "待机",
    1: "光伏与市电联合带载",
    2: "电池放电",
    3: "故障",
    4: "烧录模式",
    5: "光伏充电",
    6: "市电充电",
    7: "光伏与市电联合充电",
    8: "联合充电且旁路带载",
    9: "光伏充电 + 市电带载",
    10: "市电充电且旁路带载",
    11: "电网带载",
    12: "光伏充电 + 逆变带载",
    13: "并网发电",
    14: "光伏 + 电池给负载",
    15: "发电机充电",
    16: "发电机带载",
    17: "光伏 + 发电机给电池充电",
    18: "光伏 + 发电机给负载",
    19: "光伏充电 + 发电机带载",
    20: "发电机带载",
    21: "光伏馈网",
    22: "光伏馈网带载",
    23: "光伏充电馈网",
    24: "光伏充电带载馈网",
    25: "电池馈网",
    26: "电池馈网带载",
    27: "电池 + 光伏联合馈网",
    28: "电池 + 光伏联合带载馈网",
}

# === Growatt Input Registers（严格匹配提供的表格参数，无偏差）===
# 字段说明：
# address = 寄存器地址（与表格完全一致）
# scale = 缩放系数（来自表格，"-"设为None）
# precision = 数据显示精度（来自表格，"-"设为None）
# unit = 计量单位（来自表格，"-"设为None）
# 数据类型：表格中标注 uint16/int16，便于后续组件逻辑对接
SENSOR_REGISTERS = {
    # 数据类型：uint16
    "system_status": {
        "name": "系统状态",
        "address": 0,
        "scale": None,
        "precision": None,
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    "pv1_voltage": {
        "name": "PV1 电压",
        "address": 1,
        "scale": 0.1,
        "precision": None,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "pv2_voltage": {
        "name": "PV2 电压",
        "address": 2,
        "scale": 0.1,
        "precision": None,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "pv1_real_power": {
        "name": "PV1 实时功率",
        "address": 4,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "pv2_real_power": {
        "name": "PV2 实时功率",
        "address": 6,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "pv1_current": {
        "name": "PV1 电流",
        "address": 7,
        "scale": 0.1,
        "precision": 1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "pv2_current": {
        "name": "PV2 电流",
        "address": 8,
        "scale": 0.1,
        "precision": 1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "load_real_power": {
        "name": "负载实时功率",
        "address": 10,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_ac_apparent_power": {
        "name": "逆变器交流输出视在功率",
        "address": 12,
        "scale": 0.1,
        "precision": None,
        "unit": "VA",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "ac_charging_power": {
        "name": "市电充电功率",
        "address": 14,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "ac_charging_apparent_power": {
        "name": "市电充电视在功率",
        "address": 16,
        "scale": 0.1,
        "precision": None,
        "unit": "VA",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "battery_voltage": {
        "name": "电池电压",
        "address": 17,
        "scale": 0.01,
        "precision": 2,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "battery_soc": {
        "name": "电池 SOC",
        "address": 18,
        "scale": 1,
        "precision": None,
        "unit": "%",
        "device_class": SensorDeviceClass.BATTERY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_bus_total_voltage": {
        "name": "逆变母线总电压",
        "address": 19,
        "scale": 0.1,
        "precision": None,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "mains_voltage": {
        "name": "市电电压",
        "address": 20,
        "scale": 0.1,
        "precision": None,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "mains_frequency": {
        "name": "市电频率",
        "address": 21,
        "scale": 0.01,
        "precision": None,
        "unit": "Hz",
        "device_class": SensorDeviceClass.FREQUENCY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_output_voltage": {
        "name": "逆变器输出电压",
        "address": 22,
        "scale": 0.1,
        "precision": None,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_output_frequency": {
        "name": "逆变器输出频率",
        "address": 23,
        "scale": 0.01,
        "precision": None,
        "unit": "Hz",
        "device_class": SensorDeviceClass.FREQUENCY,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "output_dc_voltage": {
        "name": "输出直流电压",
        "address": 24,
        "scale": 0.1,
        "precision": None,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "variable_frequency_inverter_temperature": {
        "name": "变频逆变温度",
        "address": 25,
        "scale": 0.1,
        "precision": None,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "dc_inverter_temperature": {
        "name": "直流逆变温度",
        "address": 26,
        "scale": 0.1,
        "precision": None,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_load_percentage": {
        "name": "逆变器负载率",
        "address": 27,
        "scale": 0.1,
        "precision": 1,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "battery_port_voltage_dsp": {
        "name": "电池端口电压（DSP）",
        "address": 28,
        "scale": 0.01,
        "precision": 2,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "battery_bus_voltage_dsp": {
        "name": "电池母线电压（DSP）",
        "address": 29,
        "scale": 0.01,
        "precision": 2,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "total_operating_time_high": {
        "name": "总工作时长高位",
        "address": 30,
        "scale": 0.5,
        "precision": None,
        "unit": "S",
        "device_class": None,
        "state_class": None,
    },
    "total_operating_time_low": {
        "name": "总工作时长低位",
        "address": 31,
        "scale": 0.5,
        "precision": None,
        "unit": "S",
        "device_class": None,
        "state_class": None,
    },
    "pv1_temperature": {
        "name": "MPPT1 温度",
        "address": 32,
        "scale": 0.1,
        "precision": None,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "pv2_temperature": {
        "name": "MPPT2 温度",
        "address": 33,
        "scale": 0.1,
        "precision": None,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_output_current": {
        "name": "逆变器转换输出电流",
        "address": 34,
        "scale": 0.1,
        "precision": 1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_current": {
        "name": "逆变器输出电流",
        "address": 35,
        "scale": 0.1,
        "precision": 1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "mains_input_power": {
        "name": "市电输入功率",
        "address": 37,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "mains_input_apparent_power": {
        "name": "市电输入视在功率",
        "address": 39,
        "scale": 0.1,
        "precision": None,
        "unit": "VA",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "fault_code": {
        "name": "故障代码",
        "address": 40,
        "scale": None,
        "precision": None,
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    "warning_code": {
        "name": "警告代码",
        "address": 41,
        "scale": None,
        "precision": None,
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    "warning_value": {
        "name": "警告值",
        "address": 43,
        "scale": None,
        "precision": None,
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    "device_type_code_dtc": {
        "name": "设备类型代码（DTC）",
        "address": 44,
        "scale": None,
        "precision": None,
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    "today_grid_feed_energy": {
        "name": "今日向电网送电能量",
        "address": 45,
        "scale": 0.1,
        "precision": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_grid_feed_energy_high": {
        "name": "累计向电网送电能量高位",
        "address": 46,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_grid_feed_energy_low": {
        "name": "累计向电网送电能量",
        "address": 47,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "today_pv_energy": {
        "name": "光伏今日能量",
        "address": 49,
        "scale": 0.1,
        "precision": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_pv_energy_high": {
        "name": "光伏累计发电量高位",
        "address": 50,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_pv_energy": {
        "name": "光伏累计发电量",
        "address": 51,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "today_grid_charging_energy": {
        "name": "市电今日充电能量",
        "address": 57,
        "scale": 0.1,
        "precision": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_grid_charging_energy_high": {
        "name": "市电累计充电能量高位",
        "address": 58,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_grid_charging_energy": {
        "name": "市电累计充电能量",
        "address": 59,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "today_battery_discharge_energy": {
        "name": "电池今日放电能量",
        "address": 61,
        "scale": 0.1,
        "precision": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_battery_discharge_energy_high": {
        "name": "电池放电能量累计高位",
        "address": 62,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": None,
        "state_class": None,
    },
    "total_battery_discharge_energy": {
        "name": "电池放电能量累计",
        "address": 63,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "today_grid_discharge_energy": {
        "name": "市电今日放电能量",
        "address": 65,
        "scale": 0.1,
        "precision": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_grid_discharge_energy_high": {
        "name": "市电累计放电能量高位",
        "address": 66,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_grid_discharge_energy": {
        "name": "市电累计放电能量",
        "address": 67,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "mains_charging_current": {
        "name": "市电充电电流",
        "address": 68,
        "scale": 0.1,
        "precision": 1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_output_discharge_power": {
        "name": "逆变器输出放电功率",
        "address": 70,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "inverter_output_discharge_apparent_power": {
        "name": "逆变器输出放电视在功率",
        "address": 72,
        "scale": 0.1,
        "precision": None,
        "unit": "VA",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "battery_discharge_power": {
        "name": "电池放电功率",
        "address": 74,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "battery_discharge_apparent_power": {
        "name": "电池放电视在功率",
        "address": 76,
        "scale": 0.1,
        "precision": None,
        "unit": "VA",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "slave_count": {
        "name": "从机数量",
        "address": 79,
        "scale": None,
        "precision": None,
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    "mppt_fan_speed": {
        "name": "MPPT 风扇转速",
        "address": 81,
        "scale": 1,
        "precision": None,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "variable_frequency_fan_speed": {
        "name": "变频风扇转速",
        "address": 82,
        "scale": 1,
        "precision": None,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "total_charging_current": {
        "name": "总充电电流",
        "address": 83,
        "scale": 0.1,
        "precision": 1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "total_discharging_current": {
        "name": "总放电电流",
        "address": 84,
        "scale": 0.1,
        "precision": 1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "today_load_consumption": {
        "name": "负载今日消耗",
        "address": 86,
        "scale": 0.1,
        "precision": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_load_consumption_high": {
        "name": "负载累计消耗高位",
        "address": 87,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_load_consumption": {
        "name": "负载累计消耗",
        "address": 88,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "parallel_system_charging_current": {
        "name": "并联系统充电电流",
        "address": 90,
        "scale": 0.1,
        "precision": 1,
        "unit": "A",
        "device_class": SensorDeviceClass.CURRENT,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "parallel_state": {
        "name": "并联状态",
        "address": 91,
        "scale": None,
        "precision": None,
        "unit": None,
        "device_class": None,
        "state_class": None,
    },
    "today_generator_energy": {
        "name": "发电机今日能量",
        "address": 93,
        "scale": 0.1,
        "precision": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_generator_energy_high": {
        "name": "发电机累计能量高位",
        "address": 94,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_generator_energy": {
        "name": "发电机累计能量",
        "address": 95,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "generator_power": {
        "name": "发电机功率",
        "address": 96,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "generator_voltage": {
        "name": "发电机电压",
        "address": 97,
        "scale": 0.1,
        "precision": None,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "today_battery_charging_energy": {
        "name": "电池充电今日能量",
        "address": 99,
        "scale": 0.1,
        "precision": 1,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_battery_charging_energy_high": {
        "name": "电池充电累计能量高位",
        "address": 100,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "total_battery_charging_energy": {
        "name": "电池充电累计能量",
        "address": 101,
        "scale": 0.1,
        "precision": None,
        "unit": "kWh",
        "device_class": SensorDeviceClass.ENERGY,
        "state_class": SensorStateClass.TOTAL_INCREASING,
    },
    "ct_input_power": {
        "name": "CT 输入功率",
        "address": 103,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "ct_load_active_power": {
        "name": "CT 负载有功功率",
        "address": 105,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "ct_load_percentage": {
        "name": "CT 负载百分比",
        "address": 106,
        "scale": 0.1,
        "precision": None,
        "unit": "%",
        "device_class": None,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "transformer_temperature": {
        "name": "变压器温度",
        "address": 107,
        "scale": 0.1,
        "precision": None,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "llc_temperature": {
        "name": "LLC 温度",
        "address": 108,
        "scale": 0.1,
        "precision": None,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "llc_bus_total_voltage": {
        "name": "LLC 母线总电压",
        "address": 109,
        "scale": 0.1,
        "precision": None,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "llc_battery_voltage": {
        "name": "LLC 电池电压",
        "address": 110,
        "scale": 0.01,
        "precision": 2,
        "unit": "V",
        "device_class": SensorDeviceClass.VOLTAGE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    "ambient_temperature": {
        "name": "环境温度",
        "address": 111,
        "scale": 0.1,
        "precision": None,
        "unit": "°C",
        "device_class": SensorDeviceClass.TEMPERATURE,
        "state_class": SensorStateClass.MEASUREMENT,
    },
    # 数据类型：int16
    "battery_charge_discharge_power_high": {
        "name": "电池充放电功率高位",
        "address": 77,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": None,
        "state_class": None,
    },
    "battery_charge_discharge_power": {
        "name": "电池充放电功率",
        "address": 78,
        "scale": 0.1,
        "precision": None,
        "unit": "W",
        "device_class": SensorDeviceClass.POWER,
        "state_class": SensorStateClass.MEASUREMENT,
    }
}
